version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: r2s_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=r2s_api
    ports:
      - "3366:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: r2s_redis
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes  # For data persistence

volumes:
  postgres_data:
  redis_data:
