name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  create-env:
    uses: ./.github/workflows/docker-create-env.yml
  
  build:
    needs: create-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Download .env file
      uses: actions/download-artifact@v2
      with:
        name: env-file
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/r2s-api:latest